new components and notifcations
jakpolak/find-your-course pull request #17
Opened 2021-09-20 15:52 UTC by quebonafide

2021-09-21 20:51 UTC, quebonafide commented on client/components/quickSearch/quickSearch.module.scss
> +.inputStyles:focus {
corrected for all

2021-09-22 07:22 UTC, konopek94 commented on client/pages/courses/addCourse.tsx
>  import { NotoficationType } from '../../components/notifaction/types'
typo ;p

2021-09-22 07:22 UTC, konopek94 commented on client/pages/courses/addCourse.tsx
>  import { NotoficationType } from '../../components/notifaction/types'
`NotoficationType`

2021-09-22 07:22 UTC, konopek94 commented on client/components/quickSearch/index.tsx
> +            {quickSearch.map((ele: { src: string; alt: string }, index: number) => {
Could u move this inline typing `{ src: string; alt: string }` to separate type/interface?

2021-09-22 07:22 UTC, jakpolak requested changes

2021-09-22 07:22 UTC, jakpolak commented on client/components/filtr/filter.module.scss
> +  background-image: url('https://static.wixstatic.com/media/127fea_f5b57c778e3f463e9f88590afb5ed730~mv2.jpg/v1/fit/w_924,h_520/127fea_f5b57c778e3f463e9f88590afb5ed730~mv2.jpg');
The background image shouldn't be a reference to the Wix site. It is used like this multiple times so please change it in all places.

2021-09-22 07:22 UTC, jakpolak commented on client/variables/variables.ts
> +export const longTimer = 5000
I would move these variables to the Notification file. They are closely related to notifications and it feels like overkill to do it in a separate file.

2021-09-23 13:02 UTC, quebonafide commented on client/components/filtr/filter.module.scss
> +  background-image: url('https://static.wixstatic.com/media/127fea_f5b57c778e3f463e9f88590afb5ed730~mv2.jpg/v1/fit/w_924,h_520/127fea_f5b57c778e3f463e9f88590afb5ed730~mv2.jpg');
also done for add course form

2021-09-23 13:35 UTC, jakpolak approved these changes

2021-09-23 13:52 UTC, konopek94 approved these changes

2021-09-23 14:42 UTC, konopek94 commented on client/components/quickSearch/index.tsx
> +            {quickSearch.map((ele: Element) => {
better to call it as `imageElement` or sm

2021-09-24 10:39 UTC, konopek94 approved these changes

2021-09-24 10:41 UTC, merged